[env:esp32-c3-devkitm-1]
platform = espressif32 @ 6.5.0
board = esp32-c3-devkitm-1
framework = arduino
build_type = release
monitor_filters = esp32_exception_decoder
extra_scripts = build_installer.py
monitor_speed = 115200
upload_speed = 115200
board_build.flash_mode = dio
build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    ESP32Async/ESPAsyncWebServer @ ^3.7.0
    ESP32Async/AsyncTCP @ ^3.3.5
    bblanchon/ArduinoJson @ ^6.21.6
    256dpi/MQTT @ ^2.5.3
    olikraus/U8g2